uMurmur SPK update to 1.0 beta
-Fix possible bug with "su"
-Better folder management
-Use new configuration file with default privilege dropping
-Better symlinking
-OpenSSL cert generation on installation
-More logs

diff --git a/src/umurmur/scripts/prepost-common b/src/umurmur/scripts/prepost-common
--- a/src/umurmur/scripts/prepost-common
+++ b/src/umurmur/scripts/prepost-common
@@ -17,12 +17,29 @@
 # You should have received a copy of the GNU General Public License
 # along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.
 
-# Find the CPU architecture
-synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
-arch=`echo $synoinfo | cut -d_ -f2`
+# Common
+UMDIR=/usr/local/umurmur
+UMVAR=$UMDIR/var
+UMLIB=$UMDIR/lib
+UMSHR=$UMDIR/share
+UMETC=$UMDIR/etc
+UMBIN=$UMDIR/bin
+UMEXE=$UMBIN/umurmurd
+UMCRT=$UMBIN/gencert.sh
+SUEXE=/bin/su
+PSEXE=ps
+SYNO3APP=/usr/syno/synoman/webman/3rdparty
+UMUSR=root
+
+# Files
+UMLOG=$UMVAR/umurmur.log
 
 preinst ()
 {
+	# Find the CPU architecture
+	synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
+	arch=`echo $synoinfo | cut -d_ -f2`
+
 	# Check if the architecture is supported
 	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
 		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
@@ -37,28 +54,33 @@ postinst ()
 	chown -R root:root ${SYNOPKG_PKGDEST}
 
 	# Create the view directory
-	mkdir -p /usr/local/umurmur
+	mkdir -p $UMDIR
 	mkdir -p /usr/local/bin
 
 	# Create symlinks to the installation ditectory
-	ln -s ${SYNOPKG_PKGDEST}/bin /usr/local/umurmur/bin
-	ln -s ${SYNOPKG_PKGDEST}/lib /usr/local/umurmur/lib
-	ln -s ${SYNOPKG_PKGDEST}/share /usr/local/umurmur/share
-	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/umurmur/var
-	ln -s ${SYNOPKG_PKGDEST}/etc /usr/local/umurmur/etc
+	ln -s ${SYNOPKG_PKGDEST}/bin $UMBIN
+	ln -s ${SYNOPKG_PKGDEST}/lib $UMLIB
+	ln -s ${SYNOPKG_PKGDEST}/share $UMSHR
+	ln -s ${SYNOPKG_PKGDEST}/var $UMVAR
+	ln -s ${SYNOPKG_PKGDEST}/etc $UMETC
 
-	# Create symlinks
-	for bin in ${SYNOPKG_PKGDEST}/bin/umurmur*
-	do
-		ln -s $bin /usr/local/bin/`basename $bin`
-	done
-
-	# Link "share" folder for umurmur to find shared files
-	ln -s ${SYNOPKG_PKGDEST}/share/umurmur /usr/local/share/umurmur
+	# Create symlink
+	ln -s $UMEXE /usr/local/bin/`basename $UMEXE`
 
 	# Correct the files permission
 	chmod 555 /usr/local/umurmur/bin/*
-	chmod 555 /usr/local/umurmur/lib/*
+	chmod 555 /usr/local/umurmur/lib/*	
+
+	# Log installation was successful
+	echo `date`" : uMurmur SPK successfuly installed" >>  $UMLOG
+
+	# Certificate generation
+	$UMCRT > /dev/null
+	if [ $? -ne 0 ]; then
+		echo `date`" : Certificate generation failed" >> $UMLOG
+	else
+		echo `date`" : Certificate generation was successful" >> $UMLOG
+	fi
 
 	exit 0
 }
@@ -70,21 +92,15 @@ preuninst ()
 
 postuninst ()
 {
-	# Remove symlinks
-	for bin in ${SYNOPKG_PKGDEST}/bin/umurmur*
-	do
-		rm -f /usr/local/bin/`basename $bin`
-	done
+	# Remove symlink
+	rm -f /usr/local/bin/`basename $UMEXE`
 
 	# Remove symlinks from /usr/local/umurmur
-	rm -f /usr/local/umurmur/bin
-	rm -f /usr/local/umurmur/lib
-	rm -f /usr/local/umurmur/share
-	rm -f /usr/local/umurmur/var
-	rm -f /usr/local/umurmur/etc
-
-	# Remove "share" folder for umurmur to find shared files
-	rm -f /usr/local/share/umurmur
+	rm -f $UMBIN
+	rm -f $UMLIB
+	rm -f $UMSHR
+	rm -f $UMVAR
+	rm -f $UMETC
 
 	# Remove the view directory
 	rmdir /usr/local/umurmur
