Better start-stop-status for uMurmur. 1.0 final release

diff --git a/src/umurmur/scripts/start-stop-status b/src/umurmur/scripts/start-stop-status
--- a/src/umurmur/scripts/start-stop-status
+++ b/src/umurmur/scripts/start-stop-status
@@ -56,40 +56,42 @@ stop_daemon ()
 	# Log
 	echo `date`" : Stoping uMurmur..." >> $UMLOG
 
-	# Kill daemon
-	if [ -f $UMPID ]; then
-		kill `cat $UMPID`
-		echo " Done"
-	else
-		echo " Error : Can't find PID file !"
-	fi
-	sleep 1
-
-	# Wait until uMurmur is really dead (may take some time).
-	if [ $# -eq 0 ]; then
-		counter=20
-		while [ $counter -gt 0 ] 
-		do
-			daemon_status || break
-			let counter=counter-1
-			sleep 1
-		done
-	fi
-
 	# Remove the application from the main interface if it was previously added.
 	if [ -h $SYNO3APP/umurmur ]
 	then
 		rm -f $SYNO3APP/umurmur
 	fi
+
+	# Kill daemon
+	if [ -f $UMPID ]; then
+		kill `cat $UMPID`
+		rm -f $UMPID
+		echo " ok"
+	else
+		echo " error : Can't find PID file!"
+		killall umurmurd
+	fi
+	sleep 1
+
+	# Wait until uMurmur is really dead (may take some time).
+	counter=20
+	while [ $counter -gt 0 ] 
+	do
+		daemon_status || exit 0
+		let counter=counter-1
+		sleep 1
+	done
+
+	exit 1
 }
 
 reload_daemon ()
 {
 	if [ -f $UMPID ]; then
 		kill -s HUP `cat $UMPID`
-		echo " Done"
+		echo " ok"
 	else
-		echo " Error : Can't find PID file !"
+		echo " error : Can't find PID file!"
 	fi
 	sleep 1
 }
@@ -103,7 +105,7 @@ daemon_status ()
 case $1 in
 	start)
 		if daemon_status; then
-			echo "uMurmur daemon already running !"
+			echo "uMurmur daemon already running!"
 			exit 0
 		else
 			echo "Starting uMurmur daemon..."
@@ -112,7 +114,7 @@ case $1 in
 		fi
 		;;
 	stop)
-		echo "Stopping uMurmur daemon..."
+		echo -n "Stopping uMurmur daemon..."
 		stop_daemon
 		exit 0
 		;;
